geometry_msgs/Point goal # e.g. Navigation goal pose for hector quadrotor
float64 speed # target navigation speed in m/s
---
int8 return_type    # indicate the return status of the navigation task
                    # 0 Navigation succeeded.
                    # 1 Navigation failed at planning.
                    # 2 Navigation failed at execution.
                    # 3 Motor enable failed.
                    # 4 Connection lost.
                    # 5 Unknown error.